import { WebClient } from '@slack/web-api';

let slackClient: WebClient | null = null;

/**
 * Get or create the Slack WebClient instance.
 */
const getSlackClient = (): WebClient | null => {
    if (!process.env.SLACK_BOT_TOKEN) {
        console.warn('Slack bot token not configured. Slack notifications disabled.');
        return null;
    }

    if (!slackClient) {
        slackClient = new WebClient(process.env.SLACK_BOT_TOKEN);
    }
    return slackClient;
};

/**
 * Send a rich Slack notification with Block Kit formatting.
 */
const sendMessage = async (blocks: any[], text: string): Promise<boolean> => {
    const client = getSlackClient();
    if (!client || !process.env.SLACK_CHANNEL_ID) {
        console.log('[Slack] Skipped notification (not configured):', text);
        return false;
    }

    try {
        await client.chat.postMessage({
            channel: process.env.SLACK_CHANNEL_ID,
            text, // Fallback text
            blocks,
        });
        return true;
    } catch (error) {
        console.error('[Slack] Failed to send message:', error);
        return false;
    }
};

/**
 * Notify: SRS document has been generated.
 */
export const notifySRSGenerated = async (projectName: string, srsTitle: string) => {
    return sendMessage(
        [
            {
                type: 'header',
                text: { type: 'plain_text', text: '📄 SRS Document Generated', emoji: true },
            },
            {
                type: 'section',
                fields: [
                    { type: 'mrkdwn', text: `*Project:*\n${projectName}` },
                    { type: 'mrkdwn', text: `*SRS Title:*\n${srsTitle}` },
                ],
            },
            {
                type: 'context',
                elements: [
                    { type: 'mrkdwn', text: '🤖 Generated by *AIVA Agent 1 — Business Analyst*' },
                ],
            },
        ],
        `📄 SRS "${srsTitle}" generated for project "${projectName}"`
    );
};

/**
 * Notify: SRS has been approved.
 */
export const notifySRSApproved = async (srsTitle: string, approvedBy: string) => {
    return sendMessage(
        [
            {
                type: 'header',
                text: { type: 'plain_text', text: '✅ SRS Approved', emoji: true },
            },
            {
                type: 'section',
                text: { type: 'mrkdwn', text: `*${srsTitle}* has been approved by *${approvedBy}*.\nPipeline advancing to meeting scheduling.` },
            },
        ],
        `✅ SRS "${srsTitle}" approved by ${approvedBy}`
    );
};

/**
 * Notify: Meeting has been scheduled with Google Meet link.
 */
export const notifyMeetingScheduled = async (
    meetingTitle: string,
    date: string,
    meetLink: string,
    agenda: string[]
) => {
    const agendaText = (agenda || []).map((item, i) => `${i + 1}. ${item}`).join('\n');

    return sendMessage(
        [
            {
                type: 'header',
                text: { type: 'plain_text', text: '📅 Meeting Scheduled', emoji: true },
            },
            {
                type: 'section',
                fields: [
                    { type: 'mrkdwn', text: `*Meeting:*\n${meetingTitle}` },
                    { type: 'mrkdwn', text: `*Date:*\n${date}` },
                ],
            },
            {
                type: 'section',
                text: { type: 'mrkdwn', text: `*Agenda:*\n${agendaText}` },
            },
            {
                type: 'actions',
                elements: [
                    {
                        type: 'button',
                        text: { type: 'plain_text', text: '🔗 Join Google Meet', emoji: true },
                        url: meetLink,
                        style: 'primary',
                    },
                ],
            },
            {
                type: 'context',
                elements: [
                    { type: 'mrkdwn', text: '🤖 Scheduled by *AIVA Agent 2 — Coordinator*' },
                ],
            },
        ],
        `📅 Meeting "${meetingTitle}" scheduled for ${date}. Join: ${meetLink}`
    );
};

/**
 * Notify: Tasks have been created and assigned.
 */
export const notifyTasksCreated = async (projectName: string, taskCount: number, missingCount: number) => {
    return sendMessage(
        [
            {
                type: 'header',
                text: { type: 'plain_text', text: '📋 Tasks Created & Assigned', emoji: true },
            },
            {
                type: 'section',
                fields: [
                    { type: 'mrkdwn', text: `*Project:*\n${projectName}` },
                    { type: 'mrkdwn', text: `*Tasks Created:*\n${taskCount}` },
                ],
            },
            ...(missingCount > 0
                ? [
                    {
                        type: 'section',
                        text: {
                            type: 'mrkdwn',
                            text: `⚠️ *${missingCount} task(s) flagged with missing resources*. Please check the dashboard.`,
                        },
                    },
                ]
                : []),
            {
                type: 'context',
                elements: [
                    { type: 'mrkdwn', text: '🤖 Planned by *AIVA Agent 3 — Tech Lead*' },
                ],
            },
        ],
        `📋 ${taskCount} tasks created for "${projectName}". ${missingCount > 0 ? `⚠️ ${missingCount} have missing resources.` : ''}`
    );
};

/**
 * Notify: New blocker reported.
 */
export const notifyBlocker = async (description: string, reportedBy: string, aiSolution?: string) => {
    const blocks: any[] = [
        {
            type: 'header',
            text: { type: 'plain_text', text: '🚨 New Blocker Reported', emoji: true },
        },
        {
            type: 'section',
            fields: [
                { type: 'mrkdwn', text: `*Reported by:*\n${reportedBy}` },
                { type: 'mrkdwn', text: `*Status:*\n🔴 OPEN` },
            ],
        },
        {
            type: 'section',
            text: { type: 'mrkdwn', text: `*Description:*\n> ${description}` },
        },
    ];

    if (aiSolution) {
        blocks.push({
            type: 'section',
            text: { type: 'mrkdwn', text: `*🤖 AI Suggested Solution:*\n${aiSolution}` },
        });
    }

    blocks.push({
        type: 'context',
        elements: [
            { type: 'mrkdwn', text: '🤖 Detected by *AIVA Agent 4 — Scrum Master*' },
        ],
    });

    return sendMessage(blocks, `🚨 Blocker reported by ${reportedBy}: "${description}"`);
};

/**
 * Notify: Blocker has been resolved.
 */
export const notifyBlockerResolved = async (description: string) => {
    return sendMessage(
        [
            {
                type: 'header',
                text: { type: 'plain_text', text: '✅ Blocker Resolved', emoji: true },
            },
            {
                type: 'section',
                text: { type: 'mrkdwn', text: `> ${description}\n\nThis blocker has been marked as *resolved*.` },
            },
        ],
        `✅ Blocker resolved: "${description}"`
    );
};
